import dataclasses

from starkware.cairo.lang.compiler.ast.code_elements import (
    CodeElementIf,
    CodeElementFor,
)
from starkware.cairo.lang.compiler.ast.for_loop import ForClauseIn
from starkware.cairo.lang.compiler.ast.node import AstNode
from starkware.cairo.lang.compiler.ast.visitor import Visitor

ANONYMOUS_LABEL_PREFIX = "_anon_label"


def is_anonymous_label(label_name: str) -> bool:
    """
    Returns True if the given label seems to have been generated by AnonymousLabelGenerator.
    """
    return label_name.startswith(ANONYMOUS_LABEL_PREFIX)


class AnonymousLabelGenerator:
    """
    Generates anonymous labels.
    """

    def __init__(self):
        # Stores a counter for naming anonymous labels.
        self.anon_label_counter = 0

    def get(self):
        label_name = f"{ANONYMOUS_LABEL_PREFIX}{self.anon_label_counter}"
        self.anon_label_counter += 1
        return label_name

    def __eq__(self, other):
        if not isinstance(other, AnonymousLabelGenerator):
            return False
        return self.anon_label_counter == other.anon_label_counter


class UniqueLabelCreator(Visitor):
    """
    Adds unique labels to CodeElementIf elements.
    """

    def __init__(self):
        super().__init__()
        # Generates anonymous labels.
        self.anon_label_gen = AnonymousLabelGenerator()

    def _visit_default(self, elm: AstNode):
        return elm

    def visit_CodeElementIf(self, elm: CodeElementIf):
        assert elm.label_neq is None
        assert elm.label_end is None
        label_neq = self.anon_label_gen.get()
        label_end = self.anon_label_gen.get()
        return CodeElementIf(
            condition=elm.condition,
            main_code_block=self.visit(elm.main_code_block),
            else_code_block=self.visit(elm.else_code_block),
            label_neq=label_neq,
            label_end=label_end,
            location=elm.location,
        )

    def visit_CodeElementFor(self, elm: CodeElementFor):
        assert elm.label_func is None
        elm = dataclasses.replace(
            elm,
            label_func=self.anon_label_gen.get(),
            clauses=self.visit(elm.clauses),
            label_if_neq=self.anon_label_gen.get(),
            label_if_end=self.anon_label_gen.get(),
        )
        return super().visit_CodeElementFor(elm)

    def visit_ForClauseIn(self, obj: ForClauseIn):
        assert obj.label_iter is None
        return dataclasses.replace(obj, label_iter=self.anon_label_gen.get())
