from dataclasses import field


# Dollar is not a valid identifier character in Cairo, thus we can be sure,
# nobody will try to create colliding identifiers in source code.
ANONYMOUS_LABEL_PREFIX = "$"

global_counter = 0


def new_unique_label() -> str:
    """
    Returns new compilation-unique label name which is guaranteed to be impossible to declare
    by source code.
    """
    global global_counter
    global_counter += 1
    return f"{ANONYMOUS_LABEL_PREFIX}{global_counter}"


def is_anonymous_label(label_name: str) -> bool:
    """
    Returns True if the given label seems to have been generated by AnonymousLabelGenerator.
    """
    return label_name.startswith(ANONYMOUS_LABEL_PREFIX)


def unique_label_field(**kwargs):
    return field(default_factory=new_unique_label, **kwargs)
